ALTER TABLE "Party" ADD COLUMN "creditLimit" REAL;
ALTER TABLE "Party" ADD COLUMN "creditDays" INTEGER;

ALTER TABLE "PurchaseBill" ADD COLUMN "subTotalAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseBill" ADD COLUMN "gstAmount" REAL NOT NULL DEFAULT 0;

ALTER TABLE "PurchaseItem" ADD COLUMN "taxableAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseItem" ADD COLUMN "gstRateSnapshot" REAL;
ALTER TABLE "PurchaseItem" ADD COLUMN "gstAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseItem" ADD COLUMN "lineTotal" REAL NOT NULL DEFAULT 0;

ALTER TABLE "SpecialPurchaseBill" ADD COLUMN "subTotalAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "SpecialPurchaseBill" ADD COLUMN "gstAmount" REAL NOT NULL DEFAULT 0;

ALTER TABLE "SpecialPurchaseItem" ADD COLUMN "taxableAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "SpecialPurchaseItem" ADD COLUMN "gstRateSnapshot" REAL;
ALTER TABLE "SpecialPurchaseItem" ADD COLUMN "gstAmount" REAL NOT NULL DEFAULT 0;

ALTER TABLE "SalesBill" ADD COLUMN "subTotalAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "SalesBill" ADD COLUMN "gstAmount" REAL NOT NULL DEFAULT 0;

ALTER TABLE "SalesItem" ADD COLUMN "taxableAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "SalesItem" ADD COLUMN "gstRateSnapshot" REAL;
ALTER TABLE "SalesItem" ADD COLUMN "gstAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "SalesItem" ADD COLUMN "lineTotal" REAL NOT NULL DEFAULT 0;
